### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by alif338** [google-developer-training/kotlin-bootcamp#85]
**Describe the problem**
I'm try to compile the _runExample()_ function. But I have something errors:
`Exception in thread "main" java.lang.NoClassDefFoundError: example/JavaRun
	at example.FishKt.runExample(Fish.kt:48)
	at example.myapp.MainKt.main(main.kt:118)
	at example.myapp.MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: example.JavaRun
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more`

**In which step of the codelab can this issue be found?**
Step 7.

**Steps to reproduce?**
Substeps 3 : "Call JavaRun.runNow() with the object you created."

**Versions**
2020.2.3

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by stvreumi** [comment]
I also encounter this error, and I don't know how to fix this.
The code lab title is "Kotlin Bootcamp for Programmers 6: Functional manipulation"
